shared_todo_app/config/routes.rb
Rails.application.routes.draw do
  get 'todos/index'
  match "todos/add" => "todos#add", :via => :post
  get "todos/delete" => "todos#delete", :as => :delete
  match "todos/complete" => "todos#complete", :via => :post

end

shared_todo_app/app/models/todo.rb
class Todo < ActiveRecord::Base

 validates :todo_item, presence: true
end

shared_todo_app/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  # protect_from_forgery with: :exception
  def index
  
  end
end

shared_todo_app/app/controllers/todos_controller.rb
class TodosController < ApplicationController
  def index
  @todo_items = Todo.all
  #render :index, :layout => true
  end
  def delete
  @todo_last = Todo.last
  @todo_last.delete
  @todo_last.save
  end
  def add
   todo = Todo.create(:todo_item => params[:todo_text])
   if !todo.valid?
        flash[:error] = todo.errors.full_messages.join("<br>").html_safe
   end
   redirect_to :action => 'index'
  end
  def complete
    params[:todos_checkbox].each do |check|
       todo_id = check
       t = Todo.find_by_id(todo_id)
      if t.completed == true
        t.update_attribute(:completed, false)
      else
        t.update_attribute(:completed, true)
      end
     end
    redirect_to :action => 'index'
end
private
def todo_params
	params.require(:todo_item).permit(:completed)
	end
end

shared_todo_app/app/helpers/application_helper.rb
module ApplicationHelper
end

shared_todo_app/app/helpers/todos_helper.rb
module TodosHelper
end

shared_todo_app/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>SharedTodoApp</title>
  <%= stylesheet_link_tag"application",:media=>"all"%>
  <link href="/assets/application.css"media="all" rel="stylesheet" type="text/css"/>
  <%= javascript_include_tag "application" %>
  <script src="/assets/application.js" type="text/javascript"></script>
</head>
<body>
<div class="navbar">
    <div class="navbar-inner">
      <a class="brand" href="#">Just Did it</a>
    </div>
  </div>
<%= yield %>
</body>
</html>

shared_todo_app/app/views/todos/delete.html.erb
<p>Todo successfully deleted </p>
<a href="/todos/index">Back</a>

shared_todo_app/app/views/todos/index.html.erb
<title> Shared Todo App </title>
<div class="container">
  <div class="row">
		<div class="span4">
			<h1>Shared Todo App</h1>
			<hr>
			<p>All your todos here</p>
			<%= form_tag("/todos/add", :method=>"post") do %>
			<%= text_field_tag(:todo_text) %>
			<%= submit_tag("Add todo", :class=>"btn") %>
			<% end %>
			<% if !flash[:error].nil? %>
				<div class="alert alert-error">
					<button type="button" class="close" data-dismiss="alert" >×</button>
					<strong><%= flash[:error] %></strong>
					</div>
				<% end %>
			<div class="well">
				<%= form_tag("/todos/complete/", :method => "post") do %>
					<ul style="list-style-type:none;">
					<% @todo_items.each do |t| %> 
					<% if t.completed == true %>
					<li style="color:grey;"> <%= check_box_tag  "todos_checkbox[]",t.id %>  <strike><%= t.todo_item %></strike> </li>
					<% else %>
					<li> <%= check_box_tag  "todos_checkbox[]",t.id %> <%= t.todo_item %>  </li>
					<% end %>
				<%end%>
					</ul>
					<%= submit_tag("Toggle Todos", :class=>"btn btn-success") %>
					<%end %>
			</div> <!-- well -->
		</div> <!-- span4 -->
	</div> <!-- row -->
</div> <!-- container -->
<%= link_to "Delete last todo", delete_path, :class=>"btn" %>